enum ScreenNameEnum {
  //Home Screen
  HOME_TAB_SCREEN = 'HOME_TAB_SCREEN',

  //Activity Screen
  ACTIVITY_LIST_SCREEN = 'ACTIVITY_LIST_SCREEN',
  //Bottom tab screens
  LEAD_HOME_SCREEN = 'HOME_SCREEN',
  TASK_HOME_SCREEN = 'TASK_HOME_SCREEN',
  CONTENT_HOME_SCREEN = 'CONTENT_HOME_SCREEN',
  DASHBOARD_SCREEN = 'DASHBOARD_SCREEN',
  FOLLOW_UP_HOME_SCREEN = 'FOLLOW_UP_HOME_SCREEN',

  //Leads
  LEAD_PROFILE_SCREEN = 'LEAD_PROFILE_SCREEN',
  CREATE_LEAD_SCREEN = 'CREATE_LEAD_SCREEN',
  UPDATE_LEAD_SCREEN = 'UPDATE_LEAD_SCREEN',
  CALL_LOG_SCREEN = 'CALL_LOG_SCREEN',

  UPLOAD_EXCEL_FILE_SCREEN = 'UPLOAD_EXCEL_FILE_SCREEN',

  WHATSAPP_CALL_LOG = 'WHATSAPP_CALL_LOG',

  //Tasks screens
  CREATE_TASK_SCREEN = 'CREATE_TASK_SCREEN',
  UPDATE_TASK_SCREEN = 'UPDATE_TASK_SCREEN',
  CREATE_ACTIVITY_SCREEN = 'CREATE_ACTIVITY_SCREEN',
  UPDATE_ACTIVITY_SCREEN = 'UPDATE_ACTIVITY_SCREEN',
  CREATE_NOTE_SCREEN = 'CREATE_NOTE_SCREEN',
  UPDATE_NOTE_SCREEN = 'UPDATE_NOTE_SCREEN',

  //Content ScreenNames
  CREATE_MESSAGE_SCREEN = 'CREATE_MESSAGE_SCREEN',
  CREATE_FILE_SCREEN = 'CREATE_FILE_SCREEN',
  CREATE_PAGE_SCREEN = 'CREATE_PAGE_SCREEN',
  CREATE_PRODUCT_SCREEN = 'CREATE_PRODUCT_SCREEN',
  CREATE_QUOTATION_SCREEN = 'CREATE_QUOTATION_SCREEN',
  QUOTATION_DETAIL_SCREEN = 'QUOTATION_DETAIL_SCREEN',
  PRODUCT_LIST_SCREEN = 'PRODUCT_LIST_SCREEN',
  ADD_CATEGORY_SCREEN = 'ADD_CATEGORY_SCREEN',
  QUOTATION_LIST_SCREEN = 'QUOTATION_LIST_SCREEN',
  ADD_QUOTATION = 'ADD_QUOTATION',
  SHARE_CONTENT_SCREEN = 'SHARE_CONTENT_SCREEN',

  //Invoices Screens
  INVOICE_LIST_SCREEN = 'INVOICE_LIST_SCREEN',
  UPDATE_INVOICE_SCREEN = 'UPDATE_INVOICE_SCREEN',

  //Automation Screens
  AUTOMATION_LIST_SCREEN = 'AUTOMATION_LIST_SCREEN',
  UPDATE_AUTOMATION_RULE_SCREEN = 'UPDATE_AUTOMATION_RULE_SCREEN',

  //Deals Screens
  DEALS_LIST_SCREEN = 'DEALS_LIST_SCREEN',
  UPDATE_DEAL_SCREEN = 'UPDATE_DEAL_SCREEN',
  //Settings ScreenNames
  SETTINGS_TAB_SCREEN = 'SETTINGS_TAB_SCREEN',
  SETTINGS_HOME_SCREEN = 'SETTINGS_HOME_SCREEN',
  GENERAL_SETTINGS_SCREEN = 'GENERAL_SETTINGS_SCREEN',
  UPDATE_USER_PROFILE_SCREEN = 'UPDATE_USER_PROFILE_SCREEN',
  SUBSCRIPTION_SCREEN = 'SUBSCRIPTION_SCREEN',
  DISTRIBUTION_SETTING_SCREEN = 'DISTRIBUTION_SETTING_SCREEN',
  DISCLOSURE_SCREEN = 'DISCLOSURE_SCREEN',
  MANAGE_INTEGRATION_SCREEN = 'MANAGE_INTEGRATION_SCREEN',
  MANAGE_NOTIFICATION_SCREEN = 'MANAGE_NOTIFICATION_SCREEN',
  UPDATE_DISTRIBUTION_RULE = 'UPDATE_DISTRIBUTION_RULE',
  //Preferences
  MANAGE_CUSTOMIZATION = 'MANAGE_CUSTOMIZATION',
  CUSTOMIZABLE_IEEM_LIST = 'CUSTOMIZABLE_IEEM_LIST',
  UPDATE_PREFRENCE_VALUE = 'UPDATE_PREFRENCE_VALUE',

  //Manage Team
  MY_TEAM_SCREEN = 'MY_TEAM_SCREEN',
  ADD_TEAM_SCREEN = 'ADD_TEAM_SCREEN',
  ADD_TEAM_MEMBER_SCREEN = 'ADD_TEAM_MEMBER_SCREEN',

  //Static screens
  GET_HELP_SCREEN = 'GET_HELP_SCREEN',
  REFERRAL_SCREEN = 'REFERRAL_SCREEN',

  //Registration Screens
  WELCOME_SLIDER_SCREEN = 'WELCOME_SLIDER_SCREEN',
  SELECT_LANGUAGE_SCREEN = 'SELECT_LANGUAGE_SCREEN',
  REGISTRATION_SCREEN = 'REGISTRATION_SCREEN',
  ENTER_OTP_SCREEN = 'ENTER_OTP_SCREEN',
  UPDATE_BASIC_PROFILE_SCREEN = 'UPDATE_BASIC_PROFILE_SCREEN',
  APP_PERMISSION_SCREEN = 'APP_PERMISSION_SCREEN',

  //Tabs
  CONTENT_MESSAGES = 'CONTENT_MESSAGES',
  CONTENT_FILES = 'CONTENT_FILES',
  CONTENT_PAGES = 'CONTENT_PAGES',
  CONTENT_PRODUCT = 'CONTENT_PRODUCT',
  CONTENT_CATEGORY = 'CONTENT_CATEGORY',
  CONTENT_QUOTATION = 'CONTENT_QUOTATION',

  //Digital cards Screen
  DIGITAL_CARD_HOME_SCREEN = 'DIGITAL_CARD_HOME_SCREEN',
  MANAGE_DIGITAL_CARD_SCREEN = 'MANAGE_DIGITAL_CARD_SCREEN',
}

export default ScreenNameEnum;
