enum SInfoTypeEnum {
  JWT = 'JWT',
  USER_CONTEXT = 'USER_CONTEXT',
  CALLER_ID_STATUS = 'CALLER_ID_STATUS',
  CALL_RECORDING_STATUS = 'CALL_RECORDING_STATUS',
  CALL_RECORDING_PATH = 'CALLER_ID_STATUS',
}

export default SInfoTypeEnum;
