/* tslint:disable */
/**
 * Greeham API
 * This is Greeham backend services api based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Response
 */
export interface Response {
  message: string;
  data?: any;
  status: boolean;
  statusCode?: number;
}
export interface ImageResponse {
  name: string;
  path: string;
}
